databases:
  - name: conduit
    plan: free
    databaseName: conduit
    user: sushbhask

services:
  - type: web
    plan: free
    name: conduit
    runtime: python
    envVars:
      - key: PYTHON_VERSION
    value: 3.12.3    
    buildCommand: './build.sh'
    startCommand: 'python3 -m gunicorn conduit.wsgi:application' 
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: conduit
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4